/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package PersonalExpenseManager;

import java.time.LocalDate;
import java.util.List;
import java.util.Scanner;

// user put

public class App {
    /*

    1. enter an expense

        a. Enter expense type
        b. Enter Date
        c. Enter amount

    2. Show expense

    3. Quit application

     */
    static Scanner scanner = new Scanner(System.in) ;

    public static void main(String[] args) {

        ExpenseDataRepository.createTable(); // creating table when the application starts.

       int choice = 0;

        do {
            System.out.println("Option 1: Enter an expense");
            System.out.println("Option 2: Show total expense");
            System.out.println("Option 3: Quit application");
            System.out.print("Enter your Choice: ");


            choice = Integer.parseInt(scanner.nextLine());

            if (choice == 1){

                System.out.print("Enter expense type: ");
                String expenseType = scanner.nextLine();

                System.out.print("Enter Date: ");
                LocalDate dateOfPurchase = LocalDate.parse(scanner.nextLine());

                System.out.print("Enter Amount: ");
                Double amount = Double.parseDouble(scanner.nextLine());

                enterExpense(expenseType,dateOfPurchase,amount);

            }
            if(choice == 2){
                Double total = showExpenses();
                System.out.print("Your total expense is " + total);
            }

        }
        while(choice != 3);

    }
    public static ExpenseData enterExpense(String expenseType, LocalDate dateOfPurchase, Double amount) {

        ExpenseData expenseData = new ExpenseData(expenseType,dateOfPurchase,amount);
        ExpenseDataRepository expenseDataRepository = new ExpenseDataRepository();
        ExpenseData result = expenseDataRepository.create(expenseData);
        return result;

    }
    public static Double showExpenses(){
        System.out.println("Showing Expenses: ");
        ExpenseDataRepository expenseDataRepository = new ExpenseDataRepository();
        List<ExpenseData> allData = expenseDataRepository.getExpenseData();
        Double total = 0.0;
        for(int i = 0; i<allData.size();i++){
            total += allData.get(i).getAmount();
        }

        return total;
    }
}
